# Link repository to Travis CI
# https://travis-ci.org/

# Master branch only
branches:
  only:
  - master
  - dev

# Set the language
language: python
python:
    - "3.5"

before_install:
  - pip install --upgrade pip

# command to install dependencies
install:
  - pip install numpy scipy matplotlib pandas sympy nose statsmodels tabulate
  - pip install .

# command to run tests
script: nosetests
